app:
  env: str(max=200, required=True)
  log:
    level: str(max=200, required=True)
  metric:
    sampling:
      rate: int(required=True)
  name: str(max=200, required=True)
mq:
  api:
    auth:
      token: str(max=200, required=True)
  batch:
    size: int(required=True)
  cache:
    refresh:
      initial: int(required=True)
      schedule: int(required=True)
  consumer:
    enabled: bool(required=True)
    version: int(required=True)
  enabled: bool(required=True)
  env: str(max=200, required=True)
  flush:
    interval:
      millis: int(required=True)
  keep:
    alive:
      duration: int(required=True)
  max:
    idle:
      connections: int(required=True)
  open:
    circuit:
      duration: int(required=True)
  producer:
    enabled: bool(required=True)
    version: int(required=True)
  queue:
    size:
      log:
        delay:
          seconds: int(required=True)
  server:
    api:
      url: str(max=200, required=True)
    connection:
      timeouts: int(required=True)
port: int(required=True)
profiling:
  enabled: bool(required=True)
  port: int(required=True)
click:
  consumer:
    mq:
      id: int(required=True)
order:
  consumer:
    mq:
      id: int(required=True)
storage:
  scylla:
    contact:
      points: str(max=200, required=True)
    keyspace: str(max=200, required=True)
    num:
      conns: int(required=True)
    port: int(required=True)
    timeout:
      in:
        ms: int(required=True)
