{{- if and .Values.deployment .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "labels.common" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
{{- include "labels.selector" . | nindent 4 }}
spec:
  {{- with .Values.deployment.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
{{- include "labels.selector" . | nindent 6 }}
{{- with .Values.deployment.updateStrategy }}
{{ toYaml . | indent 2 -}}
{{- end }}
  template:
    metadata:
      annotations:
      {{- with .Values.deployment.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.telegraf.enabled }}
        telegraf.influxdata.com/class: "infra"
      {{- end }}
      labels:
        {{- include "labels.common" . | nindent 8 }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
{{- include "labels.selector" . | nindent 12 }}
      {{- if .Values.deployment.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.deployment.image.pullSecret }}
      {{- end }}
      {{- if .Values.deployment.volumes }}
      volumes:
        {{- toYaml .Values.deployment.volumes | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.initContainers }}
      initContainers:
        {{- toYaml .Values.deployment.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.applicationName }}
          {{- if .Values.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.deployment.volumeMounts | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.command }}
          command: {{- include "application.tplvalues.render" (dict "value" .Values.deployment.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.args }}
          args: {{- include "application.tplvalues.render" (dict "value" .Values.deployment.args "context" $) | nindent 12 }}
          {{- end }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          {{- if .Values.deployment.lifecycle }}
          lifecycle: {{ toYaml .Values.deployment.lifecycle | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.probes }}
          {{- with .liveness }}
          livenessProbe:
            {{- with .failureThreshold }}
            failureThreshold: {{ . }}
            {{- end }}
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
              scheme: {{ .scheme }}
            {{- with .periodSeconds }}
            periodSeconds: {{ . }}
            {{- end }}
            {{- with .successThreshold }}
            successThreshold: {{ . }}
            {{- end }}
            {{- with .timeoutSeconds }}
            timeoutSeconds: {{ . }}
            {{- end }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
          {{- end }}
          {{- end }}
          {{- if or .Values.externalSecret.enabled .Values.otel_enabled (and .Values.configMap .Values.configMap.enabled) }}
          envFrom:
            {{- if .Values.externalSecret.enabled }}
            - secretRef:
                name: {{ .Values.deployment.envFrom.secretRef }}
            {{- if ( default false (.Values.disasterRecovery).enabled ) }}
            - secretRef:
                name: {{ .Values.deployment.envFrom.secretRef }}-dr
            {{- end }}
            {{- end }}
            {{- if .Values.otel_enabled }}
            - secretRef:
                name: {{ .Values.deployment.envFrom.secretRef }}-otel
            {{- end }}
            {{- if and .Values.configMap .Values.configMap.enabled }}
            - configMapRef:
                name: {{ .Values.namespace }}-config
            {{- end }}
          {{- end }}
          env:
            - name: TZ
              value: Asia/Kolkata
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- if .Values.telegraf.enabled }}
            - name: TELEGRAF_UDP_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- end }}
            {{- if .Values.otel_enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(NODE_IP):4317
            {{- end }}
          {{- with .Values.deployment.env }}
            {{- range . }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          {{- end }}
          {{- with .Values.deployment.ports }}
          ports:
            {{- range . }}
          - containerPort: {{ .containerPort }}
            name: {{ .name }}
            protocol: {{ .protocol }}
            {{- end }}
          {{- end }}
          {{- if .Values.telegraf.enabled }}
          - containerPort: 9273
            name: telegraf-sc
            protocol: TCP
          {{- end }}
          {{- with .Values.deployment.probes }}
          {{- with .readiness }}
          readinessProbe:
            {{- with .failureThreshold }}
            failureThreshold: {{ . }}
            {{- end }}
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
              scheme: {{ .scheme }}
            {{- with .periodSeconds }}
            periodSeconds: {{ . }}
            {{- end }}
            {{- with .successThreshold }}
            successThreshold: {{ . }}
            {{- end }}
            {{- with .timeoutSeconds}}
            timeoutSeconds: {{ . }}
            {{- end }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
          {{- end }}
          {{- end }}
          {{- with .Values.deployment.resources }}
          resources:
            {{- with .limits }}
            limits:
              {{- with .memory }}
              memory: "{{ . }}"
              {{- end }}
              {{- with .cpu }}
              cpu: "{{ . }}"
              {{- end }}
            {{- end }}
            {{- with .requests }}
            requests:
              {{- with .memory }}
              memory: "{{ . }}"
              {{- end }}
              {{- with .cpu }}
              cpu: "{{ . }}"
              {{- end }}
            {{- end }}
          {{- end }}

      {{- with .Values.deployment.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds | default "300" }}
      {{- if .Values.deployment.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.namespace }}
      {{- end }}
      {{- if .Values.securityContext }}
      podSecurityContext:
      {{- toYaml .Values.securityContext | nindent 12 }}
      {{- end }}
{{- end }}
