arch: arm64
bu: datascience
build_tool: docker
deployArgo: true
dockerBuildVersion: go-1.22
environment:
    int:
        deployment_order:
            - online-feature-store-api
            - online-feature-store-consumer
    prd:
        deployment_order:
            - online-feature-store-api-experiment
            - online-feature-store-api
            - online-feature-store-api-mp
            - online-feature-store-consumer
            - online-feature-store-consumer-v2
            - online-feature-store-api-secondary
            - online-feature-store-consumer-v3
            - online-feature-store-consumer-v4
            - online-feature-store-consumer-realtime
            - online-feature-store-consumer-v5
            - online-feature-store-api-secondary-p2p-test
    stg:
        deployment_order:
            - online-feature-store-api
            - online-feature-store-consumer
excludedModules:
    - null
maintainer: mohit.kumar@meesho.com
modules:
    - api-server
    - consumer:
        kafka: true
notify_channel: mlp-deployments
repo_name: BharatMLStack-internal
skip_sonar: true
team: ml-platform
